### ISSUE TITLE
Could you please set a new version tag?

### ISSUE THREAD

**Issue by zhuravlev-pe** [tysonmote/gommap#11]
The latest pull request (#10) contains a critical Windows fix and is already merged. At the same time, the existing version tag 0.0.1 points at an older changeset without this fix. Is it possible to bump the version tag so that "go get github.com/tysonmote/gommap" retrieves a fixed package?

Thanks in advance!

**Comment by tysonmote** [comment]
Done! https://github.com/tysonmote/gommap/releases/tag/v0.0.2
