### ISSUE TITLE
Does the patch for MacOSX support Arm64 ? 

### ISSUE THREAD

**Issue by cschar** [tysonmote/gommap#12]
I recently switched over my go installation from amd64 to arm64 on my M1 mac so I could use the VSCode debugger functionality.

Following through this book that uses your package: 
https://github.com/travisjeffery/proglog/blob/master/WriteALogPackage/internal/log/index.go

Now I am trying to use this package and am getting the error on import

`proglog/internal/log/index.go:7:2 no required module provides package github.com/tysontate/gommap; to add it:`

**Comment by cschar** [comment]
found the actual issue,  the code was referencing your old github repository.

```
import (
	"io"
	"os"
	"github.com/tysontate/gommap"
)
```

I tried running 

```
go get github.com/tysontate/gommap
go: github.com/tysontate/gommap@v0.0.2: parsing go.mod:
	module declares its path as: github.com/tysonmote/gommap
	        but was required as: github.com/tysontate/gommap
```

So I changed the import to the updated repo and it worked (both on arm64 and amd64 mac golang installations)
```
import (
	"io"
	"os"
	"github.com/tysonmote/gommap"
	// "github.com/tysontate/gommap"
)
```

**Comment by tysonmote** [comment]
Glad it works now! I didn't realize the repo was referenced in a book. 😅
