### ISSUE TITLE
non windows examples still using launchpad.net/gocheck

### ISSUE THREAD

**Issue by splace** [tysonmote/gommap#13]
in go 1.22 i get this....

```
...imports
	github.com/tysonmote/gommap tested by
	github.com/tysonmote/gommap.test imports
	launchpad.net/gocheck: unrecognized import path "launchpad.net/gocheck": GOVCS disallows using bzr for public launchpad.net/gocheck; see 'go help vcs'
```

seems you can drop in "gopkg.in/check.v1", like has already been donw for the windows test.

**Comment by tysonmote** [comment]
Just pushed https://github.com/tysonmote/gommap/commit/a0284a9149ddfef99d0c98355f10d93aaa2f9884 -- let me know if that doesn't work for you!

**Comment by splace** [comment]
this happens when installing in 1.22, so i think to test you need to release it. i guess as a patch.

**Comment by tysonmote** [comment]
Done! I just pushed v0.0.3
